openapi: 3.0.0

info:
  title: "Interview Kuantaz"
  description: "Kuantaz technical test."
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /institution:
    post:
      operationId: "institution.create"
      tags:
        - "Institution"
      summary: "Create a new Institution"
      description: "Create a new Institution"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Institution"
      responses:
        "201":
          description: "Institution created Successfully."

    get:
      operationId: "institution.get_all"
      tags:
        - "Institution"
      summary: "List of Institutions"
      description: "Lis of Institutions"
      responses:
        "200":
          description: "Successfully Institutions."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Institution"


  /institution/{id}: 
    get:
      operationId: "institution.get"
      tags:
        - "Institution"
      summary: "Details of nstitution"
      description: "Details of institution"
      parameters:
        - name: id
          in: path
          description: Institution ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: "Successfully institutions."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Institution"
    
    put:
      operationId: "institution.update"
      tags:
        - "Institution"
      summary: "Edit institution"
      description: "Edit institution."
      parameters:
        - name: id
          in: path
          description: Institution ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Institution"
      responses:
        "200":
          description: "Successfully institution edited."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Institution"
    
    delete:
      operationId: "institution.delete"
      tags:
        - "Institution"
      summary: "Delete a institution"
      description: "Delete a institution."
      parameters:
        - name: id
          in: path
          description: Institution ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: "Successfully institution deleted."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Institution"

components:
  schemas:
    Institution:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        address:
          type: string
        date_created:
          type: string